@echo off
echo Creating launcher...
PortableApps.comLauncher\PortableApps.comLauncherGenerator.exe %CD%\PolyMCPortable
echo Creating installer...
PortableApps.comInstaller\PortableApps.comInstaller.exe %CD%\PolyMCPortable
